# products = [
#   {
#     '_id': '1',
#     'name': 'Peter England Blue Shirt',
#     'image': '/images/peter.jpg',
#     'description':
#       'Make an impression in this blue check shirt,tailored in Slim Fit from Peter England Casuals by Peter England',
#     'brand': 'Peter England',
#     'category': 'Electronics',
#     'price': 784,
#     'countInStock': 10,
#     'rating': 4.5,
#     'numReviews': 12,
#   },
#   {
#     '_id': '2',
#     'name': 'Peter England White T Shirt',
#     'image': '/images/p2.jpg',
#     'description':
#       'Add a fresh spin to your everyday style with this white solid Polo Neck T-shirt, cut for a Slim Fit from Peter England Casuals by Peter England.',
#     'brand': 'Peter England',
#     'category': 'Electronics',
#     'price': 899.99,
#     'countInStock': 0,
#     'rating': 4.0,
#     'numReviews': 8,
#     'availablesizes': ['m,',' l,',' xl'],
#   },
#   {
#     '_id': '3',
#     'name': 'Peter England Yellow Jeans',
#     'image': '/images/p3.jpg',
#     'description':
#       'Redefine your off-duty look in theseyellowDark wash jeans from Peter England Jeans by Peter England and look stylish wherever you go.',
#     'brand': 'Peter England',
#     'category': 'Electronics',
#     'price': 1062,
#     'countInStock': 5,
#     'rating': 3,
#     'numReviews': 12,
#   },
#   {
#     '_id': '4',
#     'name': 'Printed Cotton Regular Fit',
#     'image': '/images/a1.jpg',
#     'description':
#       'Redefine your off-duty look in theseyellowDark wash jeans from Peter England Jeans by Peter England and look stylish wherever you go.',
#     'brand': 'Allen Solly',
#     'category': 'Electronics',
#     'price': 1599.99,
#     'countInStock': 11,
#     'rating': 5,
#     'numReviews': 12,
#   },
#   {
#     '_id': '5',
#     'name': 'T-Shirt Reflexed Fit',
#     'image': '/images/h1.jpg',
#     'description':
#       'Redefine your off-duty look in theseyellowDark wash jeans from Peter England Jeans by Peter England and look stylish wherever you go.',
#     'brand': 'H & M',
#     'category': 'Electronics',
#     'price': 799,
#     'countInStock': 7,
#     'rating': 3.5,
#     'numReviews': 10,
#   },
#   {
#     '_id': '6',
#     'name': 'Tshirt with Mosif',
#     'image': '/images/h2.jpg',
#     'description':
#       'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
#     'brand': 'H & M',
#     'category': 'Electronics',
#     'price': 999,
#     'countInStock': 0,
#     'rating': 4,
#     'numReviews': 12,
#   },
# ]
