# Generated by Django 3.2.6 on 2021-09-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_ray'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalPriceUsd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
